using System.Text;
using System.Text.Json;

namespace fuseraft.Cli.Display;

/// <summary>
/// Reads a context-window snapshot JSONL file produced by
/// <see cref="fuseraft.Orchestration.ContextWindowRecorder"/> and writes a self-contained
/// Chart.js HTML file showing cumulative input token growth per agent over time.
/// </summary>
public static class ContextWindowRenderer
{
    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
        PropertyNamingPolicy        = JsonNamingPolicy.SnakeCaseLower,
    };

    /// <summary>
    /// Reads <paramref name="snapshotsPath"/>, filters to <paramref name="sessionId"/>,
    /// and writes a Chart.js HTML visualization to <paramref name="outputPath"/>.
    /// Returns true if the file was written, false when there are no snapshots.
    /// Never throws.
    /// </summary>
    public static async Task<bool> RenderAsync(
        string snapshotsPath,
        string outputPath,
        string sessionId)
    {
        try
        {
            var snapshots = await LoadSnapshotsAsync(snapshotsPath, sessionId);
            if (snapshots.Count == 0) return false;

            var html = BuildHtml(snapshots, sessionId);

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);

            await File.WriteAllTextAsync(outputPath, html, Encoding.UTF8);
            return true;
        }
        catch { return false; }
    }

    private static async Task<List<Snapshot>> LoadSnapshotsAsync(string path, string sessionId)
    {
        if (!File.Exists(path)) return [];

        var result = new List<Snapshot>();
        foreach (var line in await File.ReadAllLinesAsync(path))
        {
            if (string.IsNullOrWhiteSpace(line)) continue;
            try
            {
                var s = JsonSerializer.Deserialize<Snapshot>(line, JsonOpts);
                if (s is not null && string.Equals(s.Session, sessionId, StringComparison.OrdinalIgnoreCase))
                    result.Add(s);
            }
            catch { /* skip malformed lines */ }
        }
        return result;
    }

    private static string BuildHtml(List<Snapshot> snapshots, string sessionId)
    {
        // Snapshot data embedded as JSON (safe: values are numbers, bools, and ISO strings)
        var snapshotsJson = JsonSerializer.Serialize(snapshots, new JsonSerializerOptions
        {
            PropertyNamingPolicy   = JsonNamingPolicy.SnakeCaseLower,
            WriteIndented          = false,
        });

        // Extract threshold values from the first snapshot that carries them
        var warnAt    = snapshots.FirstOrDefault(s => s.WarnAt    is > 0)?.WarnAt    ?? 0;
        var cutoverAt = snapshots.FirstOrDefault(s => s.CutoverAt is > 0)?.CutoverAt ?? 0;

        return $$"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Context Window &#8212; {{sessionId}}</title>
              <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
              <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@3.0.1/dist/chartjs-plugin-annotation.min.js"></script>
              <style>
                *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
                body {
                  font-family: ui-monospace, "Cascadia Code", "Fira Code", monospace;
                  background: #0d1117;
                  color: #e6edf3;
                  padding: 24px;
                  min-height: 100vh;
                }
                header { margin-bottom: 16px; }
                header h1 { font-size: 15px; font-weight: 600; color: #e6edf3; }
                header p  { font-size: 12px; color: #8b949e; margin-top: 4px; }
                .chart-wrap {
                  background: #161b22;
                  border: 1px solid #21262d;
                  border-radius: 6px;
                  padding: 20px;
                  height: 520px;
                  position: relative;
                }
                footer { margin-top: 12px; font-size: 11px; color: #484f58; }
              </style>
            </head>
            <body>
              <header>
                <h1>Context Window Visualization</h1>
                <p>Session <code>{{sessionId}}</code> &mdash; cumulative input tokens per agent over turns</p>
              </header>
              <div class="chart-wrap">
                <canvas id="chart"></canvas>
              </div>
              <footer>
                Generated by fuseraft-cli &mdash; compaction events shown as vertical markers.
                Requires internet for Chart.js CDN.
              </footer>
              <script>
            Chart.register(window['chartjs-plugin-annotation']);

            const SNAPSHOTS = {{snapshotsJson}};
            const WARN_AT    = {{warnAt}};
            const CUTOVER_AT = {{cutoverAt}};

            // Palette: GitHub-style blues/greens/purples/oranges
            const PALETTE = [
              '#58a6ff', '#3fb950', '#d2a8ff', '#ffa657',
              '#f78166', '#79c0ff', '#56d364', '#e3b341',
            ];

            // Group agent snapshots (exclude system compaction markers from datasets)
            const agentMap = {};
            for (const s of SNAPSHOTS) {
              if (s.agent === 'system') continue;
              (agentMap[s.agent] ??= []).push(s);
            }

            const datasets = Object.entries(agentMap).map(([agent, snaps], i) => {
              const color = PALETTE[i % PALETTE.length];
              return {
                label: agent,
                data: snaps.map(s => ({ x: s.turn, y: s.cumulative_input_tokens })),
                borderColor: color,
                backgroundColor: color + '18',
                pointBackgroundColor: color,
                pointRadius: 4,
                pointHoverRadius: 6,
                borderWidth: 2,
                tension: 0.25,
                fill: false,
              };
            });

            // Compaction turn markers from system records
            const compactionTurns = SNAPSHOTS
              .filter(s => s.agent === 'system' && s.compaction_occurred)
              .map(s => s.turn);

            // Build annotations
            const annotations = {};

            if (WARN_AT > 0) {
              annotations.warnLine = {
                type: 'line',
                yMin: WARN_AT, yMax: WARN_AT,
                borderColor: '#e3b341',
                borderWidth: 1,
                borderDash: [5, 4],
                label: {
                  display: true,
                  content: 'warn_at ' + WARN_AT.toLocaleString(),
                  position: 'start',
                  color: '#e3b341',
                  backgroundColor: 'transparent',
                  font: { size: 11 },
                },
              };
            }

            if (CUTOVER_AT > 0) {
              annotations.cutoverLine = {
                type: 'line',
                yMin: CUTOVER_AT, yMax: CUTOVER_AT,
                borderColor: '#f85149',
                borderWidth: 1,
                borderDash: [5, 4],
                label: {
                  display: true,
                  content: 'cutover_at ' + CUTOVER_AT.toLocaleString(),
                  position: 'start',
                  color: '#f85149',
                  backgroundColor: 'transparent',
                  font: { size: 11 },
                },
              };
            }

            compactionTurns.forEach((turn, i) => {
              annotations['compaction_' + i] = {
                type: 'line',
                xMin: turn, xMax: turn,
                borderColor: '#8b949e',
                borderWidth: 1,
                borderDash: [3, 3],
                label: {
                  display: true,
                  content: '⚡ compact',
                  position: 'start',
                  color: '#8b949e',
                  backgroundColor: '#0d1117cc',
                  font: { size: 10 },
                  yAdjust: 8,
                },
              };
            });

            new Chart(document.getElementById('chart'), {
              type: 'line',
              data: { datasets },
              options: {
                responsive: true,
                maintainAspectRatio: false,
                interaction: { mode: 'index', intersect: false },
                scales: {
                  x: {
                    type: 'linear',
                    title: {
                      display: true,
                      text: 'Turn',
                      color: '#8b949e',
                      font: { size: 12 },
                    },
                    ticks: { color: '#8b949e', stepSize: 1 },
                    grid:  { color: '#21262d' },
                  },
                  y: {
                    title: {
                      display: true,
                      text: 'Cumulative Input Tokens',
                      color: '#8b949e',
                      font: { size: 12 },
                    },
                    ticks: {
                      color: '#8b949e',
                      callback: v => v.toLocaleString(),
                    },
                    grid: { color: '#21262d' },
                    beginAtZero: true,
                  },
                },
                plugins: {
                  legend: {
                    labels: {
                      color: '#e6edf3',
                      font: { size: 12 },
                      boxWidth: 12,
                      padding: 16,
                    },
                  },
                  tooltip: {
                    backgroundColor: '#161b22',
                    borderColor: '#30363d',
                    borderWidth: 1,
                    titleColor: '#e6edf3',
                    bodyColor: '#8b949e',
                    callbacks: {
                      title: items => 'Turn ' + items[0].parsed.x,
                      label: ctx => {
                        const snaps = SNAPSHOTS.filter(
                          s => s.agent === ctx.dataset.label && s.turn === ctx.parsed.x);
                        if (!snaps.length)
                          return ctx.dataset.label + ': ' + ctx.parsed.y.toLocaleString();
                        const s = snaps[0];
                        return [
                          ctx.dataset.label + ': ' + s.cumulative_input_tokens.toLocaleString() + ' cumulative',
                          '  └ this turn: in=' + s.turn_input_tokens.toLocaleString()
                                + '  out=' + s.turn_output_tokens.toLocaleString(),
                        ];
                      },
                    },
                  },
                  annotation: { annotations },
                },
              },
            });
              </script>
            </body>
            </html>
            """;
    }

    private sealed record Snapshot(
        string?  Ts,
        string?  Session,
        string   Agent,
        int      Turn,
        int      TurnInputTokens,
        int      TurnOutputTokens,
        int      CumulativeInputTokens,
        int?     WarnAt,
        int?     CutoverAt,
        bool?    CompactionOccurred);
}
